apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: unleash-poc-backstage-test
  annotations:
    github.com/project-slug: lehelp/unleash-poc
spec:
  type: other
  lifecycle: unknown
  owner: guests
